# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 15:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160509_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
